name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 */7 * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: dcai/metrics@master
        with:
          config_timezone: Australia/Sydney
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          # plugin_achievements: yes
          plugin_languages: yes
